server:
  port: 8761

eureka:
  instance:
    hostname: 104.248.221.83
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
